user:
  email:
    max_length: 255
    min_length: 6
  avatar:
    max_size: 80
    min_size: 50
page:
  per_page: 5
micro_post:
  max_content: 140
image:
  size: 5
  resize: 100
  type: "image/jpeg,image/gif,image/png"
  avt_size: 30
